a = 10;
b = 20;
console.log(typeof a);
myName = "Aritra";
console.log(typeof myName);
console.log(a + b);
console.log(typeof "a");
console.log(typeof 5.9);
let isAdult = true;
console.log(typeof isAdult);
isAdult = 10;
console.log(typeof isAdult);
let firstName = "Aritar Kayal";
console.log(firstName.length);
console.log(typeof firstName.length);
console.log(firstName[0]);
console.log(firstName[firstName.length - 2]);
console.log("Aritr" + " " + "Kayal");
